---
title: April Goldberg
timezone: America/New_York
collections:
  posts:
    title: Posts
    output: true
  projects:
    title: Projects
    output: false
  types:
    title: Types
    output: true
  uploads:
    title: Uploads
    output: true
footer: '&copy; 2026 April Goldberg '
defaults:
- scope:
    path: ''
    type: projects
  values:
    director: ''
    type: ''
    links:
      - title: ''
        url: ''
    images: []
sass:
  style: compressed
